package com.didi.game.domain;

import java.io.Serializable;

public class Station implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.id
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.name
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.district
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.location
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.longitude
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Double longitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.latitude
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Double latitude;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.carNum
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Integer carNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.parkStruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Integer parkStruct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.scene
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private String scene;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.totalMonthCostCash
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Float totalMonthCostCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.totalMonthCostCoupon
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Float totalMonthCostCoupon;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.otherResource
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private String otherResource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.duration
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Integer duration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column station.totalCostCash
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private Float totalCostCash;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table station
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.id
     *
     * @return the value of station.id
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.id
     *
     * @param id the value for station.id
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.name
     *
     * @return the value of station.name
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.name
     *
     * @param name the value for station.name
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.district
     *
     * @return the value of station.district
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.district
     *
     * @param district the value for station.district
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.location
     *
     * @return the value of station.location
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.location
     *
     * @param location the value for station.location
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.longitude
     *
     * @return the value of station.longitude
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Double getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.longitude
     *
     * @param longitude the value for station.longitude
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.latitude
     *
     * @return the value of station.latitude
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Double getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.latitude
     *
     * @param latitude the value for station.latitude
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.carNum
     *
     * @return the value of station.carNum
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Integer getCarNum() {
        return carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.carNum
     *
     * @param carNum the value for station.carNum
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setCarNum(Integer carNum) {
        this.carNum = carNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.parkStruct
     *
     * @return the value of station.parkStruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Integer getParkStruct() {
        return parkStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.parkStruct
     *
     * @param parkStruct the value for station.parkStruct
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setParkStruct(Integer parkStruct) {
        this.parkStruct = parkStruct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.scene
     *
     * @return the value of station.scene
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public String getScene() {
        return scene;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.scene
     *
     * @param scene the value for station.scene
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setScene(String scene) {
        this.scene = scene == null ? null : scene.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.totalMonthCostCash
     *
     * @return the value of station.totalMonthCostCash
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Float getTotalMonthCostCash() {
        return totalMonthCostCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.totalMonthCostCash
     *
     * @param totalMonthCostCash the value for station.totalMonthCostCash
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setTotalMonthCostCash(Float totalMonthCostCash) {
        this.totalMonthCostCash = totalMonthCostCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.totalMonthCostCoupon
     *
     * @return the value of station.totalMonthCostCoupon
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Float getTotalMonthCostCoupon() {
        return totalMonthCostCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.totalMonthCostCoupon
     *
     * @param totalMonthCostCoupon the value for station.totalMonthCostCoupon
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setTotalMonthCostCoupon(Float totalMonthCostCoupon) {
        this.totalMonthCostCoupon = totalMonthCostCoupon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.otherResource
     *
     * @return the value of station.otherResource
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public String getOtherResource() {
        return otherResource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.otherResource
     *
     * @param otherResource the value for station.otherResource
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setOtherResource(String otherResource) {
        this.otherResource = otherResource == null ? null : otherResource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.duration
     *
     * @return the value of station.duration
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.duration
     *
     * @param duration the value for station.duration
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column station.totalCostCash
     *
     * @return the value of station.totalCostCash
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public Float getTotalCostCash() {
        return totalCostCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column station.totalCostCash
     *
     * @param totalCostCash the value for station.totalCostCash
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    public void setTotalCostCash(Float totalCostCash) {
        this.totalCostCash = totalCostCash;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Station other = (Station) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getDistrict() == null ? other.getDistrict() == null : this.getDistrict().equals(other.getDistrict()))
            && (this.getLocation() == null ? other.getLocation() == null : this.getLocation().equals(other.getLocation()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getCarNum() == null ? other.getCarNum() == null : this.getCarNum().equals(other.getCarNum()))
            && (this.getParkStruct() == null ? other.getParkStruct() == null : this.getParkStruct().equals(other.getParkStruct()))
            && (this.getScene() == null ? other.getScene() == null : this.getScene().equals(other.getScene()))
            && (this.getTotalMonthCostCash() == null ? other.getTotalMonthCostCash() == null : this.getTotalMonthCostCash().equals(other.getTotalMonthCostCash()))
            && (this.getTotalMonthCostCoupon() == null ? other.getTotalMonthCostCoupon() == null : this.getTotalMonthCostCoupon().equals(other.getTotalMonthCostCoupon()))
            && (this.getOtherResource() == null ? other.getOtherResource() == null : this.getOtherResource().equals(other.getOtherResource()))
            && (this.getDuration() == null ? other.getDuration() == null : this.getDuration().equals(other.getDuration()))
            && (this.getTotalCostCash() == null ? other.getTotalCostCash() == null : this.getTotalCostCash().equals(other.getTotalCostCash()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getDistrict() == null) ? 0 : getDistrict().hashCode());
        result = prime * result + ((getLocation() == null) ? 0 : getLocation().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getCarNum() == null) ? 0 : getCarNum().hashCode());
        result = prime * result + ((getParkStruct() == null) ? 0 : getParkStruct().hashCode());
        result = prime * result + ((getScene() == null) ? 0 : getScene().hashCode());
        result = prime * result + ((getTotalMonthCostCash() == null) ? 0 : getTotalMonthCostCash().hashCode());
        result = prime * result + ((getTotalMonthCostCoupon() == null) ? 0 : getTotalMonthCostCoupon().hashCode());
        result = prime * result + ((getOtherResource() == null) ? 0 : getOtherResource().hashCode());
        result = prime * result + ((getDuration() == null) ? 0 : getDuration().hashCode());
        result = prime * result + ((getTotalCostCash() == null) ? 0 : getTotalCostCash().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table station
     *
     * @mbggenerated Thu Jul 19 20:31:05 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", district=").append(district);
        sb.append(", location=").append(location);
        sb.append(", longitude=").append(longitude);
        sb.append(", latitude=").append(latitude);
        sb.append(", carNum=").append(carNum);
        sb.append(", parkStruct=").append(parkStruct);
        sb.append(", scene=").append(scene);
        sb.append(", totalMonthCostCash=").append(totalMonthCostCash);
        sb.append(", totalMonthCostCoupon=").append(totalMonthCostCoupon);
        sb.append(", otherResource=").append(otherResource);
        sb.append(", duration=").append(duration);
        sb.append(", totalCostCash=").append(totalCostCash);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}